export const settingsCopy = {
  eyebrow: "PREFERENCES",
  title: "Settings",
  connections: "CONNECTIONS",
  voiceAudio: "VOICE AND AUDIO",
  experience: "EXPERIENCE",
  spokenNavigationTitle: "Spoken navigation",
  spokenNavigationDetail: "Announce each screen and its main voice commands",
  voiceTitle: "Voice and microphone",
  voiceDetail: "Ready · UK English",
  locationTitle: "Local area",
  notSet: "Not set",
  feedbackTitle: "Spoken feedback",
  feedbackDetail: "Hear! confirms completed voice actions",
  speakerTitle: "Test speaker",
  speakerDetail: "Play a short sound check",
  motionTitle: "Reduce motion",
  motionDetail: "Limit nonessential animation",
  textTitle: "Text size",
  textDetail: "Uses your device setting",
  resetTitle: "Set up Hear! again",
  resetDescription: "Clear local setup choices and reopen onboarding.",
  resetAction: "Reset setup",
  audioOutputTitle: "Audio output",
  audioOutputDetail: "This phone",
  bluetoothTitle: "Bluetooth and hearing devices",
  bluetoothDetail: "No device connected",
  internetTitle: "Internet",
  internetDetail: "Online and ready to stream",
  wifiTitle: "Wi-Fi",
  wifiDetail: "Connected to Home Wi-Fi",
  playbackTitle: "Playback preferences",
  playbackDetail: "Normal speed · No sleep timer",
  accessibilityTitle: "Accessibility",
  accessibilityDetail: "Contrast, motion and spoken feedback",
  privacyTitle: "Privacy",
  privacyDetail: "Permissions and listening data",
  diagnosticsTitle: "Improve voice matching",
  diagnosticsDetail:
    "Share redacted outcomes and timing only. No audio or full transcripts.",
  correctionsTitle: "Reset learned corrections",
  correctionsDetail: "Forget speech corrections stored on this device",
} as const;
