import type { AppIcon } from "@/types";

export const icons = {
  settings: "gearshape",
  microphone: "mic.fill",
  location: "location.fill",
  speaker: "speaker.wave.2.fill",
  textSize: "textformat.size",
  saved: "bookmark.fill",
  following: "person.2.fill",
  person: "person.crop.circle.fill",
  downloads: "arrow.down.circle.fill",
  downloadEmpty: "arrow.down.circle",
  history: "clock.fill",
  waveform: "waveform",
  success: "checkmark",
  error: "exclamationmark",
  play: "play.fill",
  pause: "pause.fill",
  back: "chevron.left",
  disclosure: "chevron.right",
  forward: "goforward.15",
  rewind: "gobackward.15",
  repeat: "repeat",
  homeTab: "house.fill",
  discoverTab: "safari.fill",
  libraryTab: "books.vertical.fill",
  close: "xmark",
  collapse: "chevron.down",
  playEmpty: "play.circle",
  savedEmpty: "bookmark",
  followingEmpty: "person.2",
  historyEmpty: "clock",
  audioOutput: "waveform",
  bluetooth: "wave.3.right",
  internet: "network",
  wifi: "wifi",
  playback: "slider.horizontal.3",
  accessibility: "accessibility",
  privacy: "hand.raised.fill",
  topicArrow: "arrow.right",
  search: "magnifyingglass",
  plus: "plus",
  queue: "list.bullet",
} as const;

export type { AppIcon };
