export const ALEXA_LOCAL_INTENT_NAMES = [
  "AMAZON.CancelIntent",
  "AMAZON.HelpIntent",
  "AMAZON.StopIntent",
  "AMAZON.NextIntent",
  "AMAZON.PreviousIntent",
  "AMAZON.RepeatIntent",
  "AMAZON.StartOverIntent",
  "AMAZON.NavigateHomeIntent",
  "AMAZON.YesIntent",
  "AMAZON.NoIntent",
  "SetPlaybackSpeedIntent",
  "IncreaseSpeedIntent",
  "DecreaseSpeedIntent",
  "RewindIntent",
  "FastForwardIntent",
  "FeedbackEnjoyedIntent",
  "FeedbackSomewhatIntent",
  "FeedbackNotEnjoyedIntent",
  "SkipFeedbackIntent",
  "ClarifySelectionIntent",
] as const;

export const ALEXA_EXTERNAL_INTENT_NAMES = [
  "AMAZON.FallbackIntent",
  "PlayContentIntent",
  "PlayLatestContentIntent",
  "PlayLocalIntent",
  "PlayRecommendationIntent",
  "ShowMoreBrowseIntent",
  "PlayByOrganizationIntent",
  "PlayPublicationIntent",
  "WhatsThisAboutIntent",
  "PlayByCreatorIntent",
  "BrowseContentIntent",
  "WhatsTrendingIntent",
  "WhoIsCreatorIntent",
  "FollowCreatorIntent",
  "UnfollowCreatorIntent",
  "ReportContentIntent",
  "ReportCreatorIntent",
  "TownCaptureIntent",
  "SetLocationIntent",
] as const;
