import type { KineticConfig } from "@/types";

export const DEFAULT_KINETIC_CONFIG: KineticConfig = {
  samplingIntervalMs: 20,
  tiltVelocityThreshold: 2.2,
  tiltHoldDurationMs: 60,
  neutralVelocityThreshold: 0.5,
  cooldownDurationMs: 350,
  shakeThresholdG: 0.75,
  shakeReleaseThresholdG: 0.25,
  shakeWindowMs: 450,
  shakeWarmupDurationMs: 400,
  shakePeakMinGapMs: 60,
  shakePeakMaxGapMs: 220,
  shakeAxisDominanceRatio: 0.7,
  shakeRequiredPeaks: 3,
  shakeGyroThresholdRadS: 0.8,
  shakeGyroCorrelationMs: 80,
  shakeRequiredGyroPeaks: 2,
  shakeCooldownDurationMs: 750,
  shakeNeutralDurationMs: 200,
  shakeNeutralGyroThresholdRadS: 0.35,
  shakeFeedbackSuppressionMs: 650,
  filterWindowSize: 5,
};
