import type { KineticConfig } from "@/types";

export const DEFAULT_KINETIC_CONFIG: KineticConfig = {
  samplingIntervalMs: 20,
  tiltVelocityThreshold: 2.2,
  tiltHoldDurationMs: 60,
  neutralVelocityThreshold: 0.5,
  cooldownDurationMs: 350,
  shakeThresholdG: 0.65,
  shakeReleaseThresholdG: 0.3,
  shakeWindowMs: 650,
  shakeWarmupDurationMs: 400,
  shakePeakMinGapMs: 50,
  shakePeakMaxGapMs: 280,
  shakeAxisDominanceRatio: 0.6,
  shakeRequiredPeaks: 3,
  shakeGyroThresholdRadS: 0.65,
  shakeGyroCorrelationMs: 120,
  shakeRequiredGyroPeaks: 2,
  shakeFallbackThresholdG: 1.1,
  shakeFallbackRequiredPeaks: 4,
  shakeFallbackWindowMs: 800,
  shakeCooldownDurationMs: 750,
  shakeNeutralDurationMs: 200,
  shakeNeutralGyroThresholdRadS: 0.35,
  shakeFeedbackSuppressionMs: 650,
  filterWindowSize: 5,
};
