import type { SpeedMultiplier, VoiceExecutorKey } from "@/types";

export const PLAYBACK_SPEED_OPTIONS = [
  0.5,
  0.75,
  1,
  1.25,
  1.5,
  2,
] as const satisfies readonly SpeedMultiplier[];

export const VOICE_EXECUTOR_KEYS: ReadonlySet<VoiceExecutorKey> = new Set([
  "navigate",
  "close",
  "cancel",
  "openLibrarySection",
  "openTopic",
  "setLocation",
  "search",
  "play",
  "pause",
  "resume",
  "next",
  "previous",
  "restart",
  "repeat",
  "seek",
  "speed",
  "speedStep",
  "saveCurrent",
  "removeSaved",
  "downloadCurrent",
  "removeDownload",
  "follow",
  "unfollow",
  "whatIsThis",
  "whoMadeThis",
  "sleepTimer",
  "cancelSleepTimer",
  "addToQueue",
  "openQueue",
  "clearQueue",
  "changeLocation",
  "help",
  "openAppSettings",
  "openAudioSettings",
  "openBluetoothSettings",
  "openInternetSettings",
  "openWifiSettings",
  "openAccessibilitySettings",
  "openLocationSettings",
  "resetVoiceCorrections",
  "readScreen",
  "accountSignIn",
  "accountSignOut",
  "onboardingContinue",
  "onboardingBack",
  "onboardingSkip",
  "onboardingSetTown",
  "onboardingRead",
  "onboardingUseSpokenSetup",
  "onboardingUseScreenControls",
  "onboardingPlaySoundCheck",
  "onboardingCannotHear",
  "onboardingUseLocation",
]);
