export const AMBIGUITY_SELECTION_LEFT_PHRASES: ReadonlySet<string> = new Set([
  "left",
  "previous",
  "previous option",
  "go left",
  "last one",
  "previous one",
]);

export const AMBIGUITY_SELECTION_RIGHT_PHRASES: ReadonlySet<string> = new Set([
  "right",
  "next",
  "next option",
  "go right",
]);

export const AMBIGUITY_REPEAT_PHRASES: ReadonlySet<string> = new Set([
  "repeat",
  "repeat options",
  "repeat the options",
  "what are my options",
  "what were the options",
  "say them again",
  "say the options again",
]);

export const AMBIGUITY_SELECT_PHRASES: ReadonlySet<string> = new Set([
  "select",
  "choose",
  "choose it",
  "choose this",
  "choose this one",
  "that one",
  "this one",
  "it",
  "yes",
  "confirm",
  "first one",
  "the first one",
  "first",
  "second one",
  "the second one",
  "second",
  "third one",
  "the third one",
  "third",
  "fourth one",
  "the fourth one",
  "fourth",
  "one",
  "two",
  "three",
  "four",
  "five",
  "1",
  "2",
  "3",
  "4",
  "5",
  "option 1",
  "option 2",
  "option 3",
  "option 4",
  "option 5",
  "option one",
  "option two",
  "option three",
  "option four",
  "option five",
  "number 1",
  "number 2",
  "number 3",
  "number 4",
  "number 5",
  "number one",
  "number two",
  "number three",
  "number four",
  "number five",
]);

export const AMBIGUITY_SELECT_CURRENT_PHRASES: ReadonlySet<string> = new Set([
  "select",
  "choose",
  "choose it",
  "choose this",
  "choose this one",
  "that one",
  "this one",
  "it",
  "yes",
  "confirm",
]);

export const FEEDBACK_RATING_BY_PHRASE: Readonly<Record<string, number>> = {
  "1": 1,
  one: 1,
  bad: 1,
  awful: 1,
  terrible: 1,
  poor: 1,
  "2": 2,
  two: 2,
  "3": 3,
  three: 3,
  okay: 3,
  "4": 4,
  four: 4,
  good: 4,
  "5": 5,
  five: 5,
  great: 5,
  excellent: 5,
  brilliant: 5,
};

export const FEEDBACK_ENTRY_PHRASES: ReadonlySet<string> = new Set([
  "give feedback",
  "feedback",
  "feedback on this",
  "feedback on this track",
  "feedback on this publication",
  "i want to leave feedback",
  "leave feedback",
  "rate this",
]);

export const FEEDBACK_SUBMIT_PHRASES: ReadonlySet<string> = new Set([
  "yes",
  "submit",
  "send it",
  "send",
]);

export const FEEDBACK_DISCARD_PHRASES: ReadonlySet<string> = new Set([
  "no",
  "never mind",
  "forget it",
]);
